### ISSUE TITLE
Forever loop in SelectEdge

### ISSUE THREAD

**Issue by ziqiwww** [YuexuanXu7/iRangeGraph#1]
I'm testing iRangeGraph single-attribute search on the sift 1M dataset. During the index-building phase, everything seems to be working well until the search procedure gets stuck on a specific query. This issue has been traced back to an infinite loop in the `SelectEdge` function. I tried regenerating the query ranges, ground truth, and the whole index using the `buildindex` command and rerun the search. The loop terminated indeed, but the program aborted due to `malloc(): unsorted double linked list corrupted`. Vector data are from http://corpus-texmex.irisa.fr./ and [this](https://github.com/user-attachments/files/17095458/ranges.zip) is the zipped range data used by the last aborted program. Any feedback would be appreciated.

**Comment by YuexuanXu7** [comment]
It seems that the vector data from the website you used is in .fvecs format. If you directly use the original file downloaded from the website, it will throw some error because the format of the .fvecs file is different from the required. Maybe you should pre-process the vector file according to the input vector file format (--data_path) in readme. The query file should also be in the format as shown in readme. If the error is not caused by this issue, please let me know.

**Comment by ziqiwww** [comment]
Thank you for getting back to me. I modified the file format, and it worked perfectly!
